variables:
  image_name: jeremygilbert/svelte-course-app

stages: 
  - build
  - test
  - pre-deploy

build_app:
  image: node:18-alpine
  stage: build
  cache: 
   - key: $CI_PROJECT_NAME-node_modules
     paths:
       - node_modules
     policy: push
   - key: $CI_PROJECT_NAME-build-$CI_COMMIT_SHORT_SHA
     paths:
       - build
     policy: push
  script:
   - npm install
   - npm run build
  tags:
    - kubernetes

UT:
   image: node:18-alpine
   stage: test
   cache: 
    - key: $CI_PROJECT_NAME-node_modules
      paths:
        - node_modules
      policy: pull   
   script:
     - npm run test  
   tags:
     - kubernetes

image_build:
  image: mattermost/podman:1.8.0
  stage: pre-deploy
  cache:
  - key: $CI_PROJECT_NAME-build-$CI_COMMIT_SHORT_SHA
    paths:
      - build
    policy: pull
  - key: $CI_PROJECT_NAME-node_modules
    paths:
      - node_modules
    policy: pull
  script:
   - version="$(grep \"version\" package.json |cut -d':' -f2|sed 's|[\",]||g').$CI_JOB_ID"
   - echo $version
   - podman build . -t $image_name:$version
   - podman login --tls-verify=false -u $docker_user -p $docker_password $registry
   - podman push $image_name:$version
  tags:
     - kubernetes
  needs:
    - build_app
    - UT