image: node:18-alpine
stages: 
  - build
  - test
  - pre-deploy


build_app:
  stage: build
  cache: 
   - key: $CI_PROJECT_NAME
     paths:
       - node_modules
     policy: pull-push
  script:
   - npm install
   - npm run build
  tags:
    - kubernetes

UT:
   stage: test
   script:
     - npm install  
     - npm run test  
   tags:
     - kubernetes

image_build:
  stage: pre-deploy
  script:
   - docker build . -t svelte-course-app:1.0.0 
  tags:
     - kubernetes