image: node:18-alpine
stages: 
  - build
  - test
  - pre-deploy
  - premote


build_app:
  stage: build
  cache: 
   - key: $CI_PROJECT_NAME
     paths:
       - node_modules
     policy: pull-push
  script:
   - npm install
   - npm run build
  tags:
    - kubernetes

UT:
   stage: test
   script:
     - npm run test  
   tags:
     - kubernetes