image: node:18-alpine
stage: 
  - build
  - test
  - pre-deploy
  - premote


build_app:
  stage: build
  tag: kubernetes
  cache: 
   - key: $CI_PROJECT_NAME
     paths:
       - node_modules
     policy: pull-push
  script:
   - npm run build