stages: 
  - build
  - test
  - pre-deploy


build_app:
  image: node:18-alpine
  stage: build
  cache: 
   - key: $CI_PROJECT_NAME-node_modules
     paths:
       - node_modules
     policy: push
   - key: $CI_PROJECT_NAME-build-$CI_COMMIT_SHORT_SHA
     paths:
       - build
  script:
   - npm install
   - npm run build
  tags:
    - kubernetes

UT:
   image: node:18-alpine
   stage: test
   script:
     - npm install  
     - npm run test  
   tags:
     - kubernetes

image_build:
  image: mattermost/podman:1.8.0
  stage: pre-deploy
  cache:
  - key: $CI_PROJECT_NAME-build-$CI_COMMIT_SHORT_SHA
    paths:
      - build
    policy: pull
  - key: $CI_PROJECT_NAME-node_modules
    paths:
      - node_modules
    policy: pull
  script:
   - podman build . -t svelte-course-app:1.0.0 
   - podman login --tls-verify=false -u $docker_user -p $docker_password $registry
   - podman push --format=docker svelte-course-app:1.0.0
  tags:
     - kubernetes